CREATE SCHEMA IF NOT EXISTS myschema;

DROP TABLE IF EXISTS myschema.product;
CREATE TABLE myschema.product
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_product
            PRIMARY KEY,

    name VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,

    price NUMERIC(10, 2) NOT NULL
        CONSTRAINT ck_product_price_non_negative CHECK (price >= 0),

    stock INTEGER NOT NULL
        CONSTRAINT ck_product_stock_non_negative CHECK (stock >= 0)
);